/* a11y-check.js - SC-500 guide
   Automated accessibility regression check, run by .github/workflows/a11y.yml.

   Serves nothing itself: point it at a running copy of the site
   (python -m http.server 8080 from the repo root) and it loads a
   representative page of every kind - dashboard, lesson with a diagram, lab,
   domain review, coverage, exam prep, mock exam, appendix - in BOTH themes,
   runs axe-core against WCAG 2.0/2.1 A and AA plus best practice, and exits 1
   if anything is found.

   A route list is used instead of crawling every page: the pages are
   generated by the same renderers, so one of each kind covers the markup, and
   the check stays fast enough to run on every push.

   Dev-time only. Playwright and axe-core are installed by the workflow and
   never shipped; the site itself stays dependency-free.

   Run locally:
     npm install --no-save playwright@1.56.0 axe-core@4.13.0
     npx playwright install chromium
     python -m http.server 8080 &
     node tools/a11y-check.js                     (BASE_URL to override)  */

'use strict';

const { chromium } = require('playwright');
const fs = require('fs');
const path = require('path');

const BASE = (process.env.BASE_URL || 'http://localhost:8080/').replace(/\/?$/, '/');
const AXE = fs.readFileSync(require.resolve('axe-core/axe.min.js'), 'utf8');

const ROUTES = [
  '#/',
  '#/module/01-01',          // lesson anatomy, knowledge check, first diagram
  '#/module/02-03',          // diagram with decision nodes
  '#/module/02-04',          // two diagrams on one page
  '#/module/00-02',          // Module 0 lesson with a diagram
  '#/lab/02-04',             // lab mode header and part tracker
  '#/domain/01',             // domain review
  '#/coverage',              // coverage matrix
  '#/prep/domain/02',        // exam prep question set
  '#/exam',                  // mock exam (practice.js)
  '#/appendix/0',            // plain content page
  '#/module/03-02',          // a lesson in Preview status (the Preview badge)
  '#/preview',               // verification watchlist: Preview and cost chips
  '#/cost'                   // cost planner: every cost level's chip
];
const THEMES = ['dark', 'light'];

/* A page is ready when its own content has rendered: the SPA fills #content
   asynchronously, and diagrams render after that. */
async function settle(page) {
  await page.waitForFunction(() => {
    const c = document.getElementById('content');
    return c && c.querySelector('h1') && !c.querySelector('.loading');
  }, null, { timeout: 20000 });
  await page.waitForTimeout(1500);
}

(async () => {
  const launch = process.env.CHROMIUM_PATH ? { executablePath: process.env.CHROMIUM_PATH } : {};
  const browser = await chromium.launch(launch);
  let failures = 0;
  const consoleErrors = [];

  for (const theme of THEMES) {
    const context = await browser.newContext({ viewport: { width: 1280, height: 900 } });
    await context.addInitScript(t => { try { localStorage.setItem('sc500:theme:v1', t); } catch (e) {} }, theme);
    const page = await context.newPage();
    page.on('pageerror', e => consoleErrors.push(`${theme} ${page.url()} :: ${e.message}`));

    for (const route of ROUTES) {
      await page.goto(BASE + route, { waitUntil: 'networkidle' });
      await settle(page);
      await page.evaluate(AXE);
      const violations = await page.evaluate(async () => {
        const r = await axe.run(document, {
          runOnly: ['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa', 'best-practice']
        });
        return r.violations.map(v => ({
          id: v.id, impact: v.impact, help: v.help,
          nodes: v.nodes.slice(0, 5).map(n => n.target.join(' '))
        }));
      });
      if (violations.length) {
        failures += violations.length;
        console.log(`FAIL  ${theme.padEnd(5)} ${route}`);
        for (const v of violations) {
          console.log(`      [${v.impact}] ${v.id}: ${v.help}`);
          v.nodes.forEach(n => console.log(`        ${n}`));
        }
      } else {
        console.log(`ok    ${theme.padEnd(5)} ${route}`);
      }
    }
    await context.close();
  }
  await browser.close();

  if (consoleErrors.length) {
    console.log('\nJavaScript errors while rendering:');
    consoleErrors.forEach(e => console.log('  ' + e));
  }
  const bad = failures + consoleErrors.length;
  console.log(bad ? `\n${failures} accessibility violation(s), ${consoleErrors.length} script error(s).`
                  : `\nClean: ${ROUTES.length} routes x ${THEMES.length} themes.`);
  process.exit(bad ? 1 : 0);
})().catch(e => { console.error(e); process.exit(1); });
